name: .NET

on: 
  workflow_dispatch:
  #push:
  #  branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build NiceCdn --no-restore
    #- name: Test
    #  run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish NiceCdn -c Release
    - name: Archive
      run: zip -r NiceCdn.zip NiceCdn/bin/Release/netcoreapp3.1/publish
    - name: create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        draft: false
        prerelease: false
        release_name: v1.0
        tag_name: v1.0
    - name: upload release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: NiceCdn.zip
        asset_name: NiceCdn.zip
        asset_content_type: application/zip
